Script to count tree sizes
chime-experiment/chimedb_dataset pull request #9
Opened 2020-07-21 19:02 UTC by nritsche

2020-08-17 18:46 UTC, jrs65 requested changes

2020-08-17 18:46 UTC, jrs65 commented on scripts/dataset_utils
> +def treesize(dataset_id):
This should have a docstring such that it gives a help message saying what it does.

2020-08-17 18:46 UTC, jrs65 commented on setup.py
> +    scripts=["scripts/dataset_utils"],
This should use the click entrypoints method of creating the script.

2020-08-31 19:04 UTC, nritsche commented
Thanks for reviewing, @jrs65 . I think I made all the additions you requested.

2020-08-31 20:39 UTC, jrs65 approved these changes
A few small comments to think about, but do what you want with them.

2020-08-31 20:39 UTC, jrs65 commented on chimedb/dataset/utils.py
> +    """Print number of nodes in a dataset tree."""
```suggestion
    """Print number of nodes in the tree containing DATASET_ID"""
```

2020-08-31 20:39 UTC, jrs65 commented on chimedb/dataset/utils.py
> +    """Print number of nodes in a dataset tree."""
I think you're typically supposed to mention the arguments when writing docstrings that end up as click help messages.

2020-08-31 20:39 UTC, jrs65 commented on chimedb/dataset/utils.py
> +    cli()
```suggestion
```
You could remove this if you don't intend for the script to be called directly.

2020-08-31 21:34 UTC, merged